
dists:
  # - RandUniform:
  #     samples: 2
  #     params:
  #       kappa:
  #         bounds: [0, 1]
  #         shortname: k

  #       sigma:
  #         bounds: [0, 20]
  #         shortname: s

  - RandUniform:
      samples: 11
      params:
        J:
          bounds: [0, 1]

system:
  templates: ['ising.py']
  pathstring: 'sims/J#{J:.6f}'
  cmd: 'python ./ising.py'
